swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Fleet Tracker API'
  description: 'このAPIはFleet TrackerのためのAPIです。'
tags:
  - name: warehouse
    description: 倉庫情報API
  - name: hello
    description: Hello API
host: 'localhost:8003'
schemes:
  - http
paths:
  /warehouses:
    get:
      tags:
        - warehouse
      summary: 倉庫一覧情報取得API
      description: '倉庫の一覧情報を取得します'
      produces:
        - application/json
      parameters:
        - name: warehouse_area_id
          in: query
          description: 倉庫エリアID
          required: false
          type: integer
      responses:
        '200':
          description: 取得成功
          schema:
            type: array
            items:
              $ref: '#/definitions/Warehouse'
  /warehouse:
    get:
      tags:
        - warehouse
      summary: 倉庫情報取得API
      description: '倉庫エリアIDまたは倉庫IDから、倉庫情報を取得するAPIです'
      produces:
        - application/json
      parameters:
        - name: warehouse_id
          in: query
          description: 倉庫ID
          required: false
          type: integer
      responses:
        '200':
          description: 取得成功
          schema:
            type: object
            $ref: '#/definitions/Warehouse'
        default:
          description: エラーレスポンス
          schema:
            type: object
            properties:
              error:
                type: string
                example: エラーメッセージ
  /hello:
    get:
      tags:
        - hello
      summary: Hello API
      description: 'Hello API'
      produces:
        - application/json
      responses:
        '200':
          description: 取得成功
          schema:
            type: string
            example: 'Hello, World!'
definitions:
  Warehouse:
    type: object
    properties:
      warehouse_id:
        type: integer
        example: 1
      warehouse_area_id:
        type: integer
        example: 11
      warehouse_name:
        type: string
        example: エルフーズ東京工場
      warehouse_latitude:
        type: number
        format: double
        example: 35.689
      warehouse_longitude:
        type: number
        format: double
        example: 139.692

externalDocs:
  description: 'Find out more about Swagger'
  url: 'http://swagger.io'
